---
run:
  timeout: 5m
  build-tags:
    - '' # sqlite3
    - postgres # postgres
  linters:
    disable-all: true
    enable:
      - govet
      - gofmt
      - goimports
      - errcheck
      - staticcheck
  linters-settings:
    errcheck:
      check-blank: true
    gofmt:
      simplify: false
