#!/bin/bash

go build -o hw

json=$(cat << EOS
[
  {
    "name":"column1",
    "type":"STRING",
    "unique":"true",
    "mode":"NULLABLE"
  },
  {
    "name":"column2",
    "type":"INTEGER",
    "precision":"3",
    "scale":"1",
    "unique":"false",
    "mode":"NULLABLE"
  },
  {
    "name":"column3",
    "type":"FLOAT",
    "precision":"3",
    "scale":"1",
    "unique":"false",
    "mode":"NULLABLE"
  },
  {
    "name":"column4",
    "type":"NUMERIC",
    "precision":"3",
    "scale":"1",
    "unique":"false",
    "mode":"NULLABLE"
  },
  {
    "name":"column5",
    "type":"BOOLEAN",
    "precision":"3",
    "scale":"1",
    "unique":"false",
    "mode":"NULLABLE"
  },
  {
    "name":"column6",
    "type":"TIMESTAMP",
    "precision":"3",
    "scale":"1",
    "unique":"false",
    "mode":"NULLABLE"
  },
  {
    "name":"column7",
    "type":"TIMESTAMP",
    "precision":"3",
    "scale":"1",
    "unique":"false",
    "mode":"NULLABLE"
  },
  {
    "name":"column8",
    "type":"DATE",
    "precision":"3",
    "scale":"1",
    "unique":"false",
    "mode":"NULLABLE"
  },
  {
    "name":"column9",
    "type":"TIME",
    "precision":"3",
    "scale":"1",
    "unique":"false",
    "mode":"NULLABLE"
  },
  {
    "name":"column10",
    "type":"TIME",
    "precision":"3",
    "scale":"1",
    "unique":"false",
    "mode":"NULLABLE"
  },
  {
    "name":"column11",
    "type":"DATETIME",
    "precision":"3",
    "scale":"1",
    "unique":"false",
    "mode":"NULLABLE",
	"from":"true"
  },
  {
    "name":"column12",
    "type":"DATETIME",
    "precision":"3",
    "scale":"1",
    "unique":"false",
    "mode":"NULLABLE",
	"to":"true"
  }
]
EOS
)

echo "$json" > schema.json
